export default [
  'Afador',
  'Affenhuahua',
  'Affenpinscher',
  'Afghan Hound',
  'Airedale Terrier',
  'Akbash',
  'Akita',
  'Alaskan Klee Kai',
  'Alaskan Malamute',
  'American Bulldog',
  'American English Coonhound',
  'American Eskimo Dog',
  'American Foxhound',
  'American Leopard Hound',
  'American Pit Bull Terrier',
  'American Pugabull',
  'American Staffordshire Terrier',
  'American Water Spaniel',
  'Anatolian Sheppard Dog',
  'Appenzeller Sennenhunde',
  'Auggie',
  'Aussiedoodle',
  'Aussiepom',
  'Australian Cattle Dog',
  'Australian Kelpie',
  'Australian Retriver',
  'Australian Shepperd',
  'Australian Sheppard Husky',
  'Australian Shepperd Lab Mix',
  'Australian Shepperd Pit Bull Mix',
  'Australian Terrier',
  'Azawakh',
  'Barbet',
  'Basenji',
  'Bassador',
  'Basset Fauve de Bretagne',
  'Basset Hound',
  'Basset Retriever',
  'Bavarian Mountain Scent Hound',
  'Beabull',
  'Beagle',
  'Beaglier',
  'Bearded Collie',
  'Bedlington Terrier',
  'Belgian Malinos',
  'Belgian Sheepdog',
  'Belgian Tervuren',
  'Berger Picard',
  'Berndoodle',
  'Bernese Mountain Dog',
  'Bichon Frise',
  'Biewer Terrier',
  'Black and Tan Coonhound',
  'Black Mouth Cur',
  'Black Russian Terrier',
  'Bloodhound',
  'Blue Lacy',
  'Bluetick Coonhound',
  'Bocker',
  'Boerboel',
  'Boglen Terrier',
  'Bolognese',
  'Borador',
  'Border Collie',
  'Border Sheepdog',
  'Border Terrier',
  'Bordoodle',
  'Borzoi',
  'BoShih',
  'Bossie',
  'Boston Boxer',
  'Boston Terrier',
  'Bouvier des Flandres',
  'Boxador',
  'Boxer',
  'Boxerdoodle',
  'Boxmatian',
  'Boykin Spaniel',
  'Boxweiler',
  'Boykin Spaniel',
  'Bracco Italiano',
  'Braque du Bourbonnais',
  'Briard',
  'Brittany',
  'Broholmer',
  'Bugg',
  'Bull Terrier',
  'Bullador',
  'Bullboxer Pit',
  'Bulldog',
  'Bullmastiff',
  'Bullmatian',
  'Cairn Terrier',
  'Canaan Dog',
  'Cane Corso',
  'Cardigan Welsh Corgi',
  'Catahoula Bulldog',
  'Carahoula Leopard Dog',
  'Caucasian Shepperd Dog',
  'Cav-a-jack',
  'Cavachon',
  'Cavador',
  'Cavalier King Charles Spaniel',
  'Carapoo',
  'Cesky Terrier',
  'Chabrador',
  'Cheagle',
  'Chesapeake Bay Retriver',
  'Chi Chi',
  'Chi Poo',
  'Chigi',
  'Chihuahua',
  'Chilier',
  'Chinese Crested',
  'Chinese Shar-Pei',
  'Chinook',
  'Chion',
  'Chipin',
  'Chiweenie',
  'Chow Chow',
  'Chow Shepperd',
  'Chug',
  'Chusky',
  "Cirneco dell' Etna",
  'Clumber Spaniel',
  'Cockalier',
  'Cockapoo',
  'Cocker Spaniel',
  'Collier',
  'Corgi Inu',
  'Corgidor',
  'Corman Shepperd',
  'Coton de Tulear',
  'Curly-Coated Retriever',
  'Dachsador',
  'Dachshund',
  'Dalmatian',
  'Dandie Dinmont Terrier',
  'Daniff',
  'Deutscher Wactelhund',
  'Doberdor',
  'Doberman Pinscher',
  'Docker',
  'Dogo Agentino',
  'Dogue de Bordeaux',
  'Dorgi',
  'Dorkie',
  'Doxiepoo',
  'Doxie',
  'Drentsche Patrijshond',
  'Drever',
  'Dutch Shepperd',
  'English Cocker Spaniel',
  'English Foxhound',
  'English Setter',
  'English Springer Spaniel',
  'English Toy Spaniel',
  'Entlebucher Mounain Dog',
  'Estrela Mountain Dog',
  'Eurasier',
  'Field Spaniel',
  'Finnish Lapphund',
  'Finnish Spitz',
  'Flat-Coated Retriever',
  'Fox Terrier',
  'French Bulldog',
  'French Spaniel',
  'Frenchton',
  'Frengle',
  'German Pinscher',
  'German Shepperd Dog',
  'German Sheprador',
  'German Shorthaired Pointer',
  'German Spitz',
  'German Wiredhaired Pointer',
  'Giant Schnauzer',
  'Glen of Iman Terrier',
  'Goberian',
  'Goldador',
  'Golden Cocker Retriever',
  'Golden Mountain Dog',
  'Golden Retriever',
  'Golden Retriever Corgi',
  'Golden Shepperd',
  'Goldendoodle',
  'Gollie',
  'Gordon Setter',
  'Great Dane',
  'Great Pyrenees',
  'Greater Swiss Mountain Dog',
  'Greyador',
  'Greyhound',
  'Hamiltonstovare',
  'Hanoverian Scenthound',
  'Harrier',
  'Havanese',
  'Hokkaido',
  'Horgi',
  'Huskita',
  'Huskydoodle',
  'Ibizan Hound',
  'Icelandic Sheepdog',
  'Irish Red and White Setter',
  'Irish Setter',
  'Irish Terrier',
  'Irish Water Spaniel',
  'Irish Wolfhound',
  'Italian Greyhound',
  'Jack Chi',
  'Jack Russell Terrier',
  'Jack-A-Poo',
  'Japanese Chin',
  'Japanese Spitz',
  'Karelian Bear Dog',
  'Keeshond',
  'Kerry Blue Terrier',
  'Komondor',
  'Kooikerhondje',
  'Korean Jindo Dog',
  'Kuvasz',
  'Kyi-Leo',
  'Lab Pointer',
  'Labernese',
  'Labmaraner',
  'Labrebull',
  'Labradane',
  'Labradoodle',
  'Labrador Retriever',
  'Labrastaff',
  'Labsky',
  'Lagotto Romagnolo',
  'Lakeland Terrier',
  'Lancashire Heeler',
  'Leonberger',
  'Lhasa Apso',
  'Lhasapoo',
  'Lowchen',
  'Maltese Shih Tzu',
  'Maltipoo',
  'Manchester Terrier',
  'Mastador',
  'Mastiff',
  'Miniature Pinscher',
  'Miniature Schnauzer',
  'Morkie',
  'Mudi',
  'Mutt',
  'Neapolitan Mastiff',
  'Newfoundland',
  'Norfork Terrier',
  'Norwegian Buhund',
  'Norwegian Elkhound',
  'Norwegian Lundehund',
  'Norwich Terrier',
  'Nova Scotia Duck Tolling Retriever',
  'Old English Sheepdog',
  'Otterhound',
  'Papillon',
  'Papipoo',
  'Peekapoo',
  'Pekingese',
  'Pembroke Welsh Corgi',
  'Petit Basset Griffon Vendeen',
  'Pharaoh Hound',
  'Pitsky',
  'Plott',
  'Pocket Beagle',
  'Pointer',
  'Polish Lowland Sheepdog',
  'Pomapoo',
  'Pomchi',
  'Pomeagle',
  'Pomeranian',
  'Pomsky',
  'Poochon',
  'Poodle',
  'Portuguese Podengo Pequeno',
  'Portuguese water Dog',
  'Pug',
  'Pugalier',
  'Puggle',
  'Puli',
  'Pyrenean Shepherd',
  'Rat Terrier',
  'Redbone Coonhound',
  'Rhodesian Ridgeback',
  'Rottador',
  'Rottle',
  'Rottweiler',
  'Saint Berdoodle',
  'Saint Bernard',
  'Saluki',
  'Samoyed',
  'Samusky',
  'Schipperke',
  'Schnoodle',
  'Scottish Deerhound',
  'Scottish Terrier',
  'Sealyham Terrier',
  'Sheepadoodle',
  'Shepsky',
  'Shetland Sheepdog',
  'Shiba Inu',
  'Shichon',
  'ShihTzu',
  'Shih-Poo',
  'Shiranian',
  'Shollie',
  'Shorkie',
  'Siberian Husky',
  'Silken Windhound',
  'Silky Terrier',
  'Skye Terrier',
  'Sloughi',
  'Small Musterlander Pointer',
  'Soft Coated Wheaten Terrier',
  'Spanish Mastiff',
  'Springador',
  'Stabyhoun',
  'Staffordshire Bull Terrier',
  'Standard Schnauzer',
  'Sussex Spaniel',
  'Swedish Vallhund',
  'Terripoo',
  'Texas Heeler',
  'Tebetan Mastiff',
  'Tebetan Spaniel',
  'Tebetan Terrier',
  'Toy Fox Terrier',
  'Treeing Tennessee Brindle',
  'Treeing Walker Coonhound',
  'Valley Bulldog',
  'Vizsla',
  'Weimaraner',
  'Welsh Springer Spaniel',
  'Welsh Terrier',
  'Welsh Highland White Terrier',
  'Westiepoo',
  'Whippet',
  'Whoodle',
  'Wiredhair Pointing Griffon',
  'Xoloitzcuintli',
  'Yorkipoo',
  'Yorkshire Terrier',
  'Others',
];
