export default {
  DRAWER_VALUES: {
    EDIT_DOG_PROFILE: 2,
    TRANSFER_DOG: 3,
    ADD_MORE_DOGS: 5,
    DELETE_DOG_PROFILE: 6,
    DELETE_ACCOUNT: 7,
    LOGOUT: 8,
    SCAN_DOGE_NOSE: 1,
    RESET_PIN: 4,
    DOG_BREEDER: 9,
    MISSING_DOG_LIST: 10,
    THANKS_MESSAGE: 11,
    NOTIFICATION: 12,
  },
  USER_TYPE: [
    {label: 'Dog owner', value: 'Dog owner'},
    {label: 'Dog breeder', value: 'Dog breeder'},
  ],
  COUNTRY_DATA: [
    {
      label: 'United Kingdom',
      value: 'United Kingdom',
    },
    {
      label: 'Argentina',
      value: 'Argentina',
    },
    {label: 'Australia', value: 'Australia'},
    {label: 'Austria', value: 'Austria'},
    {label: 'Belarus', value: 'Belarus'},
    {label: 'Belgium', value: 'Belgium'},
    {label: 'Brazil', value: 'Brazil'},
    {label: 'Bulgaria', value: 'Bulgaria'},
    {label: 'Canada', value: 'Canada'},
    {label: 'Chile', value: 'Chile'},
    {label: 'China', value: 'China'},
    {label: 'Croatia', value: 'Croatia'},
    {label: 'Cuba', value: 'Cuba'},
    {label: 'Cyprus', value: 'Cyprus'},
    {
      label: 'Czech Republic',
      value: 'Czech Republic',
    },
    {label: 'Denmark', value: 'Denmark'},
    {label: 'Egypt', value: 'Egypt'},
    {label: 'Estonia', value: 'Estonia'},
    {label: 'Finland', value: 'Finland'},
    {label: 'France', value: 'France'},
    {label: 'Georgia', value: 'Georgia'},
    {label: 'Greece', value: 'Greece'},
    {label: 'Hungary', value: 'Hungary'},
    {label: 'Iceland', value: 'Iceland'},
    {label: 'India', value: 'India'},
    {label: 'Ireland', value: 'Ireland'},
    {label: 'Israel', value: 'Israel'},
    {label: 'Italy', value: 'Italy'},
    {label: 'Jamaica', value: 'Jamaica'},
    {label: 'Japan', value: 'Japan'},
    {label: 'Kuwait', value: 'Kuwait'},
    {label: 'Latvia', value: 'Latvia'},
    {
      label: 'Liechtenstein',
      value: 'Liechtenstein',
    },
    {label: 'Lithuania', value: 'Lithuania'},
    {label: 'Luxembourg', value: 'Luxembourg'},
    {label: 'Malaysia', value: 'Malaysia'},
    {label: 'Malta', value: 'Malta'},
    {label: 'Mauritius', value: 'Mauritius'},
    {label: 'Moldova', value: 'Moldova'},
    {label: 'Monaco', value: 'Monaco'},
    {label: 'Montenegro', value: 'Montenegro'},
    {label: 'Netherlands', value: 'Netherlands'},
    {label: 'New Zealand', value: 'New Zealand'},
    {label: 'Norway', value: 'Norway'},
    {label: 'Pakistan', value: 'Pakistan'},
    {label: 'Paraguay', value: 'Paraguay'},
    {label: 'Philippines', value: 'Philippines'},
    {label: 'Poland', value: 'Poland'},
    {label: 'Portugal', value: 'Portugal'},
    {label: 'Qatar', value: 'Qatar'},
    {label: 'Romania', value: 'Romania'},
    {label: 'Russia', value: 'Russia'},
    {label: 'Saudi Arabia', value: 'Saudi Arabia'},
    {label: 'Serbia', value: 'Serbia'},
    {label: 'Singapore', value: 'Singapore'},
    {label: 'Slovakia', value: 'Slovakia'},
    {label: 'South Africa', value: 'South Africa'},
    {
      label: 'South Korea',
      value: 'South Korea',
    },
    {label: 'Spain', value: 'Spain'},
    {label: 'Sri Lanka', value: 'Sri Lanka'},
    {label: 'Sweden', value: 'Sweden'},
    {label: 'Switzerland', value: 'Switzerland'},
    {label: 'Thailand', value: 'Thailand'},
    {label: 'Tunisia', value: 'Tunisia'},
    {label: 'Turkey', value: 'Turkey'},
    {label: 'Ukraine', value: 'Ukraine'},
    {
      label: 'United Arab Emirates',
      value: 'United Arab Emirates',
    },
    {
      label: 'United States of America',
      value: 'United States of America',
    },
    {label: 'Uruguay', value: 'Uruguay'},
    {label: 'Venezuela', value: 'Venezuela'},
    {label: 'Vietnam', value: 'Vietnam'},
  ],
  DOG_BREEDS: [
    {label: 'Labrador Retriever', value: 'Labrador Retriever'},
    {label: 'French Bulldog', value: 'French Bulldog'},
    {label: 'German Shepherd ', value: 'German Shepherd '},
    {label: 'Golden Retriever ', value: 'Golden Retriever '},
    {label: 'Bulldog', value: 'Bulldog'},
    {label: 'Poodle', value: 'Poodle'},
    {label: 'Beagle', value: 'Beagle'},
    {label: 'Rottweiler', value: 'Rottweiler'},
    {label: 'Dachshund ', value: 'Dachshund '},
  ],
  TITLE_DATA: [
    {value: 'Mr', label: 'Mr'},
    {value: 'Mrs', label: 'Mrs'},
    {value: 'Miss', label: 'Miss'},
    {value: 'Ms', label: 'Ms'},
    {value: 'Sir', label: 'Sir'},
    {value: 'Madam', label: 'Madam'},
  ],
};
